services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog.Api/Dockerfile
    ports:
      - "6000:8080"
  
  catalog.db:
    image: postgres:latest
   
  basket.db:
    image: postgres:latest
  
  redis.cache:
    image: redis
 
  pgAdmin:
    image: dpage/pgadmin4
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Basket.Api/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount.Grpc/Dockerfile

volumes:
  pgdata:
    driver: local
  basket_data:
 


